FILMDOMS #18 메인페이지의 Critic 섹션 구현
FILMDOM-s/film-doms pull request #20
Opened 2023-02-23 14:59 UTC by SH-Lee2

제목 : FILMDOMS #18  메인페이지의 Critic 섹션 구현

<작업 내용>

- Critic 섹션 구현 (북마크 제외)

<첨부>

![image](https://user-images.githubusercontent.com/59095793/220924935-30b07a55-6ef7-4c06-a3e4-d2a5b97e07ff.png)

- 모바일
![localhost_3000_(iPhone SE)](https://user-images.githubusercontent.com/59095793/220925161-4428b45e-b86a-4eb6-b8ef-c667d536d2b0.png)

- 태블릿
![localhost_3000_](https://user-images.githubusercontent.com/59095793/220926052-012d9753-b5bd-48e8-9255-815fb009bff9.png)

- 랩탑
![1024](https://user-images.githubusercontent.com/59095793/220925385-dfe87ddd-542f-4ecc-9ddf-2f5b6d3195f2.png)

- 데스크탑
![1440](https://user-images.githubusercontent.com/59095793/220925470-c3281188-43cf-409b-9eac-075d0d950454.png)

<관련된 이슈, 커밋, PR>

- ISSUE #18

2023-02-23 15:29 UTC, chigomuh commented
고생하셨습니다. 코드에 리뷰 남겨놨습니다~!

2023-02-24 10:15 UTC, thewoowon commented
수고하셨어요. 리뷰 체크 했습니다.

2023-02-24 11:33 UTC, chigomuh requested changes
오타부분은 수정해주시면 감사하겠습니다.

2023-02-24 12:13 UTC, SH-Lee2 commented on components/views/Home/Critic/Critics.tsx
> +        <Link key={critic.id} className="critic" href={`critic/${critic.id}`}>
상대 경로라서 메인 페이지에서는 동작하는데...
critic 페이지에서는 이상하게 동작할 거 같아 수정했습니다!

2023-02-24 14:25 UTC, chigomuh commented
고생하셨습니다 !!

2023-02-24 14:54 UTC, chigomuh approved these changes

2023-02-25 02:47 UTC, merged